In [25]:
import numpy as np


In [33]:
v = np.array([[4,5,6]])
w = np.array([[100,20,30]]).T

v + w

array([[104, 105, 106],
       [ 24,  25,  26],
       [ 34,  35,  36]])

# ex01

In [26]:
v = np.array([1, 2])
w = np.array([4, -6])

v + w

array([ 5, -4])

In [27]:
def calcVecNorm(v):
    return np.sqrt(sum([v1**2 for v1 in v]))

w = np.array([0,0,1])
print( calcVecNorm(w) )

w = np.array([1,2,3])
print( calcVecNorm(w),np.linalg.norm(w) )

1.0
3.7416573867739413 3.7416573867739413


# ex 3

In [28]:
def calcDanVec(V):
    return V / calcVecNorm(V)
w = np.array([0,0,0])
print(calcDanVec(w))
# 답은 nan nan nan


[nan nan nan]


C:\Users\5jun99\AppData\Local\Temp\ipykernel_5840\3156300470.py:2: RuntimeWarning: invalid value encountered in divide
  return V / calcVecNorm(V)


# ex 4

In [29]:
def calcSomeVec(size, V):
    return size * calcDanVec(V)
a = 16
v = np.array([13, 5, 12])
print(calcSomeVec(a, v))

[11.3137085   4.35142635 10.44342323]


# ex 5


In [30]:
v = np.array([[13, 5, 12]])
vt = np.zeros((3,1))

for i in range( len(v[0])):
    vt[i][0] = v[0][i]
    
vt

array([[13.],
       [ 5.],
       [12.]])

# ex 6


In [31]:

# some vector
c = np.random.randn(5)

# squared norm as dot product with itself
sqrNrm1 = np.dot(c,c)

# squared norm via our function from exercise 1
sqrNrm2 = calcVecNorm(c)**2

# print both to confirm they're the same
print( sqrNrm1 )
print( sqrNrm2 )

2.8722700172206257
2.872270017220626
